dist: xenial
language: ruby
before_install:
- sudo apt-get install python3-pip python3-setuptools
install:
- bundle install
- pip3 install pyyaml
script: "./scripts/cibuild"
deploy:
  provider: pages
  local-dir: "./_site"
  skip-cleanup: true
  github-token:
    secure: B6HdduMp+td9XDdCg292XADb7uwDfOoHJIG8QdMFdK566TBJ3BHD7CIneGxPxYPCxVOCNYYReO5xJd3yg+9++yIy/4q8Q/j+cKyAKe39gBL/09W0kNcUIAsc/JCi4T3H6xhB2SXQc6PChaG/JmmJvQCXEETN4JK5e1/Lomd0VrZF57aGvtMIP6A+whj9z/zCPKcF4aSuEDM4V+7o2kmGrPfRe3nEi+z/EHulvVgm0phK4j4Z6rlwzpXtoWyPnaiO2IZ+gRU8C7sqjwWQSGoicmfoYmJJhCjiwZqAyOb+g0eh0auIqDOZ1BvSKL4bwx2FkJCH69JdJhK5StbGRZexIhlal/NuxBgbQxHO6eNaNNPPTeM4uo5113ibD5mTm4bgQhjnFQrNQ9vSTKvjWULg+xn/+G2+QW9aw7OwRwHEqRekIHImZSd4MWa6Z8GEvZhyv0bSmAP4rpL0L7PNU0qrXalFgcrywA263zlv0LyvikbPFYEj1XoBInKXu+IHlc8pR0mJS9LIV5OnvXynNAPvYhjQ3xdVGybYirkFtoq9gbiuFD471kEurYXrinsKnPhSNc5aCfL8RLk+XowgJmKrLtO0ULoX2Lry5KSpY7BBfgjZEQ+mMzmV2rMhh86nFKbZQnWln5Wm6/HE5iPKCATG6F5HH8As55l2KYfiOL1kSBs=
  keep-history: false
  on:
    branch: master
cache:
- bundler
- pip
