
title: stempel data collection
description: collection of all benchmark data obtained by using the stempel tool chain

show_downloads: false

theme: jekyll-theme-dinky

include: ['stencils', 'machine_files']
