# All paths are either absolute or relative in regard to this file's location
jobs_dir: ../jobs
hosts_file: hosts.yml
machinefiles_dir: ../machine_files
kernels_file: kernels.yml
namedkernels_dir: ../kernels

# Notebooks to use for workloads, selected by kernel type:
report_templates:
  # kerneltype: ipython-notebook.ipynb
  likwid-bench: report-likwid-bench.ipynb
  named: report-named-stempel.ipynb
  stempel: report-named-stempel.ipynb
